### ISSUE TITLE
"Mass" is a useless quantity on standard output 

### ISSUE THREAD

**Issue by thijsheus** [microhh/microhh2#34]
Mass only gives the average value of whatever the first scalar may be (e.g., nr, in the case of RICO).

**Comment by thijsheus** [comment]
Need to recode the conservation case to use the netcdf file, and then it can go away; possibly replaced with LWP?

**Comment by thijsheus** [comment]
Mass is now removed; need to fix the conservation case accordingly

**Comment by Chiil** [comment]
Fixed
