### ISSUE TITLE
Convert microhh 1 to microhh 2 structure

### ISSUE THREAD

**Issue by thijsheus** [microhh/microhh2#7]

**Comment by thijsheus** [comment]
TODO in general:
*) Include Cuda
*) Include tmp mechanism
*) Go through commits on microhh 1 since october
*) Make sure the code compiles after every (set of) files
*) Testcases:

TODO per file:
*) doubles become <TF>, except for time variables
*) Everything in namespace
*) No need to use new & delete
*) Constructor changes
*) Iterators on auto
*) Switches on enum classes
*) Put computations in kernels

Files to do:
force (update)
advec*
diff*
boundary*
budget*
buffer
column
cross
dump
press
thermo*

**Comment by Chiil** [comment]
Do not switch all `doubles` to `float` immediately, but only those that are passed to computational kernels
